version: '3.3'
services:
    jahia:
        image: '${JAHIA_IMAGE}'
        container_name: jahia
        ports:
            - '${JAHIA_PORT}:8080'
        environment:
            - SUPER_USER_PASSWORD=${JAHIA_PASSWORD}
            - NEXUS_USERNAME=${NEXUS_USERNAME}
        extra_hosts:
            - ${JAHIA_HOST}:127.0.0.1
        networks:
            - stack
    # Cypress container
    cypress:
        image: '${TESTS_IMAGE}'
        # https://github.com/cypress-io/cypress/issues/350
        ipc: host
        container_name: cypress
        depends_on:
            - jahia
        environment:
            - JAHIA_USERNAME=root
            - JAHIA_URL=${JAHIA_URL}
            - JAHIA_HOST=${JAHIA_HOST}
            - JAHIA_PORT=${JAHIA_PORT}
            - SUPER_USER_PASSWORD=${SUPER_USER_PASSWORD}
            - NEXUS_USERNAME=${NEXUS_USERNAME}
        networks:
            - stack
networks:
    stack:
