version: 2.1

commands:
  generate_cachekey_seed:
      description: Generate Cache Key Seeds
      steps:
      - run: 
          name: Generate Cache Key Seeds
          command: |
            find . -name 'pom.xml' | sort | xargs cat > ~/source/maven_cache_seed

references:
  workdir: &workdir
    working_directory: ~/source

  persist-workspace: &persist-workspace
    persist_to_workspace:
      root: ~/source
      paths:
        - .

  attach-workspace: &attach-workspace
    attach_workspace:
      at: .

jobs:
  checkout:
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - generate_cachekey_seed
      - *persist-workspace

  build:
    parameters:
      is_pull_request:
        type: boolean
        default: false
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    resource_class: xlarge
    steps:
      - *attach-workspace
      - restore_cache:
          keys:
            - v1-maven-dependencies-{{ checksum "maven_cache_seed" }}
            - v1-maven-dependencies-
      - run:
          name: Get the code signing certificate
          command: |
            CODE_SIGNING_CERTIFICATE_URL=$(echo $CODE_SIGNING_CERTIFICATE_ENCRYPTED_URL | sed -r 's/(.{64})/\1\n/g' | openssl enc -base64 -d -aes-256-cbc -nosalt -md md5 -pass pass:$CODE_SIGNING_CERTIFICATE_ENCRYPTION_PWD)
            if [ ! -d /home/circleci/source/.codesign/ ]; then
              mkdir /home/circleci/source/.codesign/
            fi
            CODE_SIGNING_CERTIFICATE_URL=${CODE_SIGNING_CERTIFICATE_URL%$'\r'}
            curl ${CODE_SIGNING_CERTIFICATE_URL} --output /home/circleci/source/.codesign/jahia-code-signing-certificate.p12
      - unless:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: mvn clean deploy
                command: mvn -s .circleci/.circleci.settings.xml -U -e clean deploy -Pinstaller,sign-installer-jar,windows-installer,sign-installer-exe -Djahia.sign.keystore=/home/circleci/source/.codesign/jahia-code-signing-certificate.p12 -Djahia.sign.storepass=$CODE_SIGNING_PWD
      - when:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: mvn clean install
                command: mvn -s .circleci/.circleci.settings.xml -U -e clean install -Pinstaller,sign-installer-jar,windows-installer,sign-installer-exe -Djahia.sign.keystore=/home/circleci/source/.codesign/jahia-code-signing-certificate.p12 -Djahia.sign.storepass=$CODE_SIGNING_PWD
      - unless:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: Copy artifacts to rqa2
                command: scp -o "ProxyCommand=ssh -o StrictHostKeyChecking=no -W %h:%p -p 220 jahia-ci@circleci-bastion-prod.jahia.com" -o StrictHostKeyChecking=no package/jahia-installer-package/target/Jahia-* bamboo@rqa2.int.jahia.com:/home/bamboo/qa-tools/fixCreator/jahiaInstallers
      - save_cache:
          paths:
            - ~/.m2
          key: v1-maven-dependencies-{{ checksum "maven_cache_seed" }}
      - run:
           name: Copy artifacts
           command: |
             mkdir /tmp/artifacts/
             cp /home/circleci/source/package/jahia-installer-package/target/*.jar /tmp/artifacts/
             cp /home/circleci/source/package/jahia-installer-package/target/*.exe /tmp/artifacts/
             cp /home/circleci/source/package/jahia-installer-package/target/*db-scripts.zip /tmp/artifacts/
      - store_artifacts:
           path: /tmp/artifacts/
      - *persist-workspace

  sonar:
    parameters:
      is_pull_request:
        type: boolean
        default: false
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    resource_class: xlarge
    steps:
      - *attach-workspace
      - restore_cache:
          keys:
            - v1-maven-dependencies-{{ checksum "maven_cache_seed" }}
            # fallback to using the latest cache if no exact match is found
            - v1-maven-dependencies-
      - restore_cache:
          keys:
            - v1-sonar-owasp-dependencies-<<parameters.is_pull_request>>
            - v1-sonar-owasp-dependencies-
      - when:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: Analyze pull request with sonar
                command: |
                  mvn -s .circleci/.circleci.settings.xml sonar:sonar -Dsonar.pullrequest.branch=$CIRCLE_BRANCH \
                  -Dsonar.pullrequest.key=<< pipeline.parameters.pull_request_number >> \
                  -Dsonar.pullrequest.base=<< pipeline.parameters.target_branch >> \
                  -Dsonar.pullrequest.github.repository=<< pipeline.parameters.github_repository >>
      - unless:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: Sonar analysis
                environment: 
                  DEPENDENCY_CHECK_SETTINGS: -DfailOnError=false -DskipProvidedScope=true -DskipTestScope=false 
                      -DretireJsAnalyzerEnabled=false -DnodeAnalyzerEnabled=false -Dformats=HTML,JSON 
                      -Dsonar.dependencyCheck.jsonReportPath=target/dependency-check-report.json 
                      -Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html 
                      -DdataDirectory=/home/circleci/.owasp/dependency-check-data 
                      -DsuppressionFile=.circleci/owasp-suppressions.xml
                command: |
                  if [[ "${CIRCLE_BRANCH}" == "master" ]];
                  then
                    mvn -s .circleci/.circleci.settings.xml dependency-check:aggregate sonar:sonar \
                        $DEPENDENCY_CHECK_SETTINGS
                  else
                    mvn -s .circleci/.circleci.settings.xml dependency-check:aggregate sonar:sonar \
                        -Dsonar.branch.name=$CIRCLE_BRANCH $DEPENDENCY_CHECK_SETTINGS
                  fi
      - save_cache:
          paths:
            - ~/.owasp/dependency-check-data
            - ~/.sonar/cache
          key: v1-sonar-owasp-dependencies-<<parameters.is_pull_request>>

  trigger_ee_build:
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - run:
          name: Trigger the build of jahia-ee
          command: curl -X POST --url 'https://circleci.com/api/v2/project/gh/Jahia/jahia-ee/pipeline'
            --header 'circle-token:'"$CIRCLECI_PIPELINE_LAUNCH_TOKEN"''
            --header 'content-type:application/json'
            --data '{ "branch":"'"$CIRCLE_BRANCH"'" }'

# Pipeline parameter must be declared
parameters:
  run_pull_request:
    type: boolean
    default: false
  target_branch:
    type: string
    default: ""
  pull_request_number:
    type: string
    default: ""
  github_repository:
    type: string
    default: ""

workflows:
  # This one is run only when triggered with the API, using a GitHub action
  pull_request:
    when: << pipeline.parameters.run_pull_request >>
    jobs:
      - checkout:
          name: PR Checkout
      - build:
          name: PR Build Jahia Pack
          is_pull_request: true
          context:
            - QA_ENVIRONMENT
            - jahia-code-signing
          requires:
            - PR Checkout
      - sonar:
          name: PR Sonar analysis of the pull request
          is_pull_request: true
          context: QA_ENVIRONMENT
          requires:
            - PR Build Jahia Pack
  on-code-change:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - master
                - /feature-.*/
                - /JAHIA-[0-9]-[0-9]-[0-9]-X-BRANCH/
      - build:
          name: Build Jahia Pack
          is_pull_request: false
          context:
            - QA_ENVIRONMENT
            - jahia-code-signing
          requires:
            - checkout
      - sonar:
          name: Sonar analysis
          is_pull_request: false
          context: QA_ENVIRONMENT
          requires:
            - Build Jahia Pack
      - trigger_ee_build:
          name: Trigger build of jahia-ee
          context: QA_ENVIRONMENT
          requires:
            - Build Jahia Pack
