version: 2.1

jobs:
  hello_world:
    resource_class: small
    docker:
      - image: cimg/node:lts
    steps:
      - run: |
          echo "hello world! - Workflow to be deleted once CircleCI is disabled"

workflows:
  hello_world:
    jobs:
      - hello_world