version: 2.1

orbs:
  jahia-modules-orb: jahia/jahia-modules-orb@0.8.5

# Pipeline parameter must be declared
parameters:
  run_pull_request:
    type: boolean
    default: false
  target_branch:
    type: string
    default: ""
  pull_request_number:
    type: string
    default: ""
  github_repository:
    type: string
    default: ""
  JAHIA_LATEST_MAINTENANCE_BRANCH:
    type: string
    default: "JAHIA-7-3-X-X-BRANCH"
  SSH_KEY_FINGERPRINT:
    type: string
    default: "f4:0e:08:4c:00:5d:d8:e6:74:d5:0d:4f:62:fe:e5:02"

commands:
  generate_cachekey_seed:
      description: Generate Cache Key Seeds
      steps:
      - run: 
          name: Generate Cache Key Seeds
          command: |
            find . -name 'pom.xml' | sort | xargs cat > ~/source/maven_cache_seed

references:
  workdir: &workdir
    working_directory: ~/source

  persist-workspace: &persist-workspace
    persist_to_workspace:
      root: ~/source
      paths:
        - .

  attach-workspace: &attach-workspace
    attach_workspace:
      at: .

jobs:
  checkout:
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - checkout
      - generate_cachekey_seed
      - *persist-workspace

  build:
    parameters:
      is_pull_request:
        type: boolean
        default: false
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    resource_class: xlarge
    steps:
      - *attach-workspace
      - restore_cache:
          keys:
            - v1-maven-dependencies-{{ checksum "maven_cache_seed" }}
            - v1-maven-dependencies-
      - unless:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: mvn clean deploy
                command: mvn -s .circleci/.circleci.settings.xml -U -e clean deploy -Pinstaller,windows-installer
      - when:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: mvn clean install
                command: mvn -s .circleci/.circleci.settings.xml -U -e clean install -Pinstaller,windows-installer 
      - save_cache:
          paths:
            - ~/.m2
          key: v1-maven-dependencies-{{ checksum "maven_cache_seed" }}
      - run:
           name: Copy artifacts
           command: |
             mkdir /tmp/artifacts/
             cp /home/circleci/source/package/jahia-installer-package/target/*.jar /tmp/artifacts/
             cp /home/circleci/source/package/jahia-installer-package/target/*.exe /tmp/artifacts/
             cp /home/circleci/source/package/jahia-installer-package/target/*db-scripts.zip /tmp/artifacts/
      - store_artifacts:
           path: /tmp/artifacts/
      - *persist-workspace

  code-sign:
    <<: *workdir
    docker:
      - image: cimg/openjdk:11.0-node
    resource_class: large
    steps:
      - *attach-workspace
      - jahia-modules-orb/code-signer:
          ssh_key_fingerprint: << pipeline.parameters.SSH_KEY_FINGERPRINT >>
          installer_dir: "~/source/package/jahia-installer-package/target"
          file_pattern: "Jahia-*Distribution*"
      - store_artifacts:
          path: /tmp/signed-installers
      - persist_to_workspace:
          root: ~/
          paths:
            - source/package/jahia-installer-package/target


  sonar:
    parameters:
      is_pull_request:
        type: boolean
        default: false
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    resource_class: xlarge
    steps:
      - *attach-workspace
      - restore_cache:
          keys:
            - v1-maven-dependencies-{{ checksum "maven_cache_seed" }}
            # fallback to using the latest cache if no exact match is found
            - v1-maven-dependencies-
      - restore_cache:
          keys:
            - v1-sonar-owasp-dependencies-<<parameters.is_pull_request>>
            - v1-sonar-owasp-dependencies-
      - when:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: Analyze pull request with sonar
                command: |
                  mvn -s .circleci/.circleci.settings.xml sonar:sonar -Dsonar.pullrequest.branch=$CIRCLE_BRANCH \
                  -Dsonar.pullrequest.key=<< pipeline.parameters.pull_request_number >> \
                  -Dsonar.pullrequest.base=<< pipeline.parameters.target_branch >> \
                  -Dsonar.pullrequest.github.repository=<< pipeline.parameters.github_repository >>
      - unless:
          condition: <<parameters.is_pull_request>>
          steps:
            - run:
                name: Sonar analysis
                environment: 
                  DEPENDENCY_CHECK_SETTINGS: -DfailOnError=false -DskipProvidedScope=true -DskipTestScope=false 
                      -DretireJsAnalyzerEnabled=false -DnodeAnalyzerEnabled=false -Dformats=HTML,JSON 
                      -Dsonar.dependencyCheck.jsonReportPath=target/dependency-check-report.json 
                      -Dsonar.dependencyCheck.htmlReportPath=target/dependency-check-report.html 
                      -DdataDirectory=/home/circleci/.owasp/dependency-check-data 
                      -DsuppressionFile=.circleci/owasp-suppressions.xml
                command: |
                  if [[ "${CIRCLE_BRANCH}" == "master" ]];
                  then
                    mvn -s .circleci/.circleci.settings.xml dependency-check:aggregate sonar:sonar \
                        $DEPENDENCY_CHECK_SETTINGS
                  else
                    mvn -s .circleci/.circleci.settings.xml dependency-check:aggregate sonar:sonar \
                        -Dsonar.branch.name=$CIRCLE_BRANCH $DEPENDENCY_CHECK_SETTINGS
                  fi
      - save_cache:
          paths:
            - ~/.owasp/dependency-check-data
            - ~/.sonar/cache
          key: v1-sonar-owasp-dependencies-<<parameters.is_pull_request>>

  trigger_ee_build:
    <<: *workdir
    docker: # run the steps with Docker
      - image: circleci/openjdk:8-jdk-stretch
    steps:
      - run:
          name: Trigger the build of jahia-ee
          command: curl -X POST --url 'https://circleci.com/api/v2/project/gh/Jahia/jahia-ee/pipeline'
            --header 'circle-token:'"$CIRCLECI_PIPELINE_LAUNCH_TOKEN"''
            --header 'content-type:application/json'
            --data '{ "branch":"'"$CIRCLE_BRANCH"'", "parameters":{ "is_triggered":true } }'

workflows:
  # This one is run only when triggered with the API, using a GitHub action
  pull_request:
    when: << pipeline.parameters.run_pull_request >>
    jobs:
      - checkout:
          name: PR Checkout
      - build:
          name: PR Build Jahia Pack
          is_pull_request: true
          context:
            - QA_ENVIRONMENT
          requires:
            - PR Checkout
      - code-sign:
          name: Sign installer files
          requires:
            - PR Build Jahia Pack
          context:
            - code-signing-orb
      - sonar:
          name: PR Sonar analysis of the pull request
          is_pull_request: true
          context: QA_ENVIRONMENT
          requires:
            - Sign installer files
  on-code-change:
    jobs:
      - checkout:
          filters:
            branches:
              only:
                - master
                - /feature-.*/
                - /JAHIA-[0-9]+-[X0-9]+-[X0-9]+-X-BRANCH/
      - build:
          name: Build Jahia Pack
          is_pull_request: false
          context:
            - QA_ENVIRONMENT
          requires:
            - checkout
      - code-sign:
          name: Sign installer files
          requires:
            - Build Jahia Pack
          context:
            - code-signing-orb
      - sonar:
          name: Sonar analysis
          is_pull_request: false
          context: QA_ENVIRONMENT
          requires:
            - Sign installer files
      - trigger_ee_build:
          name: Trigger build of jahia-ee
          context: QA_ENVIRONMENT
          requires:
            - Sign installer files

  scheduled:
    triggers:
      - schedule:
          # At minute 0 past hour 4, 10, and 16 on every day-of-week from Monday through Friday
          cron: "0 4,10,16 * * 1-5"
          filters:
            branches:
              only:
                - master
                - << pipeline.parameters.JAHIA_LATEST_MAINTENANCE_BRANCH >>
    jobs:
      - checkout:
          name: Scheduled checkout
      - build:
          name: Scheduled build
          context:
            - QA_ENVIRONMENT
          requires:
            - Scheduled checkout
      - code-sign:
          name: Sign installer files
          requires:
            - Scheduled build
          context:
            - code-signing-orb
#      - integration_tests:
#          name: Scheduled integration tests
#          context: QA_ENVIRONMENT
#          requires:
#            - Scheduled build
      - trigger_ee_build:
          name: Trigger build of jahia-ee
          context: QA_ENVIRONMENT
          requires:
            - Sign installer files
